github: [devinschumacher]
open_collective: devinschumacher
custom: [
  "https://apps.serp.co/serp-video-tools",
  "https://extensions.serp.co/extensions/serp/serp-video-tools",
  "https://serp.co/products/serp-video-tools/",
]
